# Generated by Django 3.1.5 on 2021-02-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210125_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='img',
        ),
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
