# Generated by Django 3.1.5 on 2021-02-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210201_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.BinaryField(null=True),
        ),
    ]
