# Generated by Django 3.1.5 on 2021-02-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20210205_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='picture',
            field=models.BinaryField(editable=True, null=True),
        ),
    ]
