version: 0.2
run-as: root
artifacts:
  files:
    - '**/*'
phases:
    install:
        runtime-versions:
            python: 3.7
        commands:
        - ls -hal
    build:
        commands:
        -  mysql -h $RdsEndpoint -u root -prrrrr < DumpDjangoDb.sql 
        # replace connection string in appsettings.json
        # MakeFile build (dotnet publish)
        - make build