version: 0.2
run-as: root
artifacts:
  files:
    - '**/*'
phases:
    install:
        runtime-versions:
            python: 3.7
        commands:
        - apt-get update -y
        - apt-get install mysql-client -y
        - ls -hal
    build:
        commands:
        - mysql -h $DbHost -u admin -pCoucou123! < sql_backup/DumpDjangoDb.sql
        - sed -i "s#db_user#${DbUser}#g" disquaire_project/settings.py
        - sed -i "s#db_password#${DbPassword}#g" disquaire_project/settings.py
        - sed -i "s#db_host#${DbHost}#g" disquaire_project/settings.py
        # replace connection string in appsettings.json
        # MakeFile build (dotnet publish)
        # - virtualenv env -p python3
        # - . env/bin/activate
        # - make init